regions:
  서울:
    - name: 강남구
      code: "11680"
    - name: 강동구
      code: "11740"
    - name: 강북구
      code: "11305"
    - name: 강서구
      code: "11500"
    - name: 관악구
      code: "11620"
    - name: 광진구
      code: "11215"
    - name: 구로구
      code: "11530"
    - name: 금천구
      code: "11545"
    - name: 노원구
      code: "11350"
    - name: 도봉구
      code: "11320"
    - name: 동대문구
      code: "11230"
    - name: 동작구
      code: "11590"
    - name: 마포구
      code: "11440"
    - name: 서대문구
      code: "11410"
    - name: 서초구
      code: "11650"
    - name: 성동구
      code: "11200"
    - name: 성북구
      code: "11290"
    - name: 송파구
      code: "11710"
    - name: 양천구
      code: "11470"
    - name: 영등포구
      code: "11560"
    - name: 용산구
      code: "11170"
    - name: 은평구
      code: "11380"
    - name: 종로구
      code: "11110"
    - name: 중구
      code: "11140"
    - name: 중랑구
      code: "11260"

  경기남부:
    - name: 수원시장안구
      code: "41111"
    - name: 수원시권선구
      code: "41113"
    - name: 수원시팔달구
      code: "41115"
    - name: 수원시영통구
      code: "41117"
    - name: 성남시수정구
      code: "41131"
    - name: 성남시중원구
      code: "41133"
    - name: 성남시분당구
      code: "41135"
    - name: 안양시만안구
      code: "41171"
    - name: 안양시동안구
      code: "41173"
    - name: 안산시단원구
      code: "41273"
    - name: 안산시상록구
      code: "41271"
    - name: 용인시처인구
      code: "41461"
    - name: 용인시기흥구
      code: "41463"
    - name: 용인시수지구
      code: "41465"
    - name: 화성시
      code: "41590"
    - name: 평택시
      code: "41220"
    - name: 오산시
      code: "41370"
    - name: 군포시
      code: "41410"
    - name: 의왕시
      code: "41430"
    - name: 과천시
      code: "41290"
    - name: 시흥시
      code: "41390"
    - name: 광명시
      code: "41210"
    - name: 안성시
      code: "41550"

  경기동부:
    - name: 하남시
      code: "41450"
    - name: 광주시
      code: "41610"
    - name: 이천시
      code: "41500"
    - name: 여주시
      code: "41670"
    - name: 양평군
      code: "41830"
    - name: 구리시
      code: "41310"
    - name: 남양주시
      code: "41360"
    - name: 가평군
      code: "41820"
